export const noPrompts = [
  'hey this is not the right button',
  'you keep pressing me and ill get mad',
  'ok keep going lets see what happens',
  'keep going i can be here all day long',
  'youre just wasting your energy at this point',
  'yawn yawn yawn',
  'you need to get outside more instead of pressing me',
  'tick tock hello is anyone there, stop pressing me',
  'how about you stop pressing me and go do something else',
  'sooner or later youll realize that pressing me is not the answer',
  'dont you have better things to do',
  'dont you have better places to be',
  'im not going to change my mind',
  'are you even reading these???',
  'i am a machine! i can outlast you!',
  'at this point its just getting sad',
  'but we might as well see how many messages i have',
  'just press the green button!',
  'ok fine you win, press the green button!',
];
