export const noPrompts = [
  'hey this is not the right button',
  'you keep pressing me and ill get mad',
  'ok keep going lets see what happens',
  'youre just wasting your energy at this point',
  'yawn yawn yawn',
  'you need to get outside more instead of pressing me',
  'how about you stop pressing me and go do something else',
  'sooner or later youll realize that pressing me is not the answer',
  'dont you have better things to do',
  'are you even reading these???',
  'i am a machine! i can outlast you!',
  'at this point its just getting sad',
  'just press the green button!',
  'ok fine you win, press the green button!',
];
